name: CI Pipeline

on:
  push:
    branches:
      - main # Запуск при пуше в ветку main
  pull_request:
    branches:
      - main # Запуск при пулл-реквестах в main

jobs:
  build-and-lint:
    runs-on: ubuntu-latest # Используем последнюю версию Ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Получаем код из репозитория

      - name: Set up Python
        uses: actions/setup-python@v5 # Настраиваем Python
        with:
          python-version: '3.10' # Или '3.13.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint # Установка линтера

      - name: Run Pylint
        run: pylint faiss_utils.py gmail_utils.py main.py ollama_utils.py # <--- ЭТУ СТРОКУ НУЖНО ИЗМЕНИТЬ
        # Возможно, потребуется настроить .pylintrc для игнорирования некоторых предупреждений

      - name: Check Dockerfile syntax
        run: docker build . --file Dockerfile --no-cache --pull --quiet || exit 1
        # Это просто проверка, что Dockerfile корректен и образ собирается.

  publish-docker-image:
    needs: build-and-lint # Запустится только после успешного линтинга и проверки Dockerfile
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Публиковать только для main ветки

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: dxrklxrd/ai-email-support-clothing-store:latest # Замените на ваш Docker Hub username